### ISSUE TITLE
[2020] Wanted features

### ISSUE THREAD

**Issue by NotWoods** [ubccsss/tcf#2]
Ideas for the next version of the Technical Career Fair site.
- [x] Responsive design (aka have a desktop version)
- [x] Show detailed company info in company list, possibly with the option to collapse
- [x] Include table numbers in alphabetical company list
- [x] Company "View on Map" link is missing banner, navigation
- [x] Fix scrolling on Privacy page
- [ ] Access prior years of the career fair, so students can get an idea who would come
- [ ] Make company groups public
- [ ] Move to Netlify
- [ ] Add offline support with a Service Worker
